apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ucla-forum
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/cs144-25s-brandonle/bruinhottake/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: ALLOWED_ORIGINS
          value: "https://bruinhottake.brandonle.dev"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: database-url
        - name: REDIS_URL
          value: "redis://redis-service.ucla-forum.svc.cluster.local:6379"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: jwt-secret
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: smtp-host
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: smtp-port
        - name: SMTP_SECURE
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: smtp-secure
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: smtp-user
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: smtp-pass
        - name: R2_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: r2-storage-secrets
              key: r2-access-key-id
        - name: R2_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: r2-storage-secrets
              key: r2-secret-access-key
        - name: R2_ACCOUNT_ID
          valueFrom:
            secretKeyRef:
              name: r2-storage-secrets
              key: r2-account-id
        - name: R2_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: r2-storage-secrets
              key: r2-bucket-name
        - name: R2_PUBLIC_DEV_URL
          valueFrom:
            secretKeyRef:
              name: r2-storage-secrets
              key: r2-public-dev-url
        - name: R2_TOKEN
          valueFrom:
            secretKeyRef:
              name: r2-storage-secrets
              key: r2-token
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        startupProbe:
          httpGet:
            path: /api/health
            port: 3001
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ucla-forum
spec:
  selector:
    app: backend
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP