apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ucla-forum-ingress
  namespace: ucla-forum
  annotations:
    # GKE-specific annotations
    kubernetes.io/ingress.global-static-ip-name: "bruinhottake-ip"
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
    networking.gke.io/managed-certificates: "ucla-forum-cert"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - host: bruinhottake.brandonle.dev
    http:
      paths:
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-service
            port:
              number: 3001
      - path: /socket.io/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-service
            port:
              number: 3001
      - path: /ws/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-service
            port:
              number: 3001
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend-service
            port:
              number: 3000