apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - certificate.yaml
  - redis.yaml

namespace: ucla-forum 